// gameplay/storyData.js
// Canon narrative runtime data for Acts I-II.

export const WORLD_STATE_DEFS = {
  WORLD_NORMAL: {
    id: 'WORLD_NORMAL',
    act: 1,
    label: 'Gutter scelle',
    desc: 'Faux ciel bleu, eau terne, ruines fracturees cachees.',
  },
  A1_LUMEN_WATER_HINT: {
    id: 'A1_LUMEN_WATER_HINT',
    act: 1,
    label: 'Lueurs sous les puits',
    desc: 'Certains points d eau brillent faiblement la nuit.',
  },
  A1_VAEL_DORN_ARCHIVE_READ: {
    id: 'A1_VAEL_DORN_ARCHIVE_READ',
    act: 1,
    label: 'Archive de Vael-Dorn lue',
    desc: 'Le joueur apprend que le monde est une decharge divine sous dome.',
  },
  SKY_DOME_FIRST_CRACK: {
    id: 'SKY_DOME_FIRST_CRACK',
    act: 1,
    label: 'Fracture du Ciel',
    desc: 'Skybox fracturee, eau emissive, debris divins et poches de gravite.',
  },
  A1_ASH_GUARDIAN_DEFEATED: {
    id: 'A1_ASH_GUARDIAN_DEFEATED',
    act: 1,
    label: 'Gardien des Cendres vaincu',
    desc: 'Le premier fragment de Verrou Celeste est obtenu.',
  },
  A2_IRONRAIN_STARTED: {
    id: 'A2_IRONRAIN_STARTED',
    act: 2,
    label: 'Pluie de Fer',
    desc: 'La Tour d Orval expulse du metal vivant dans le biome ironrain.',
  },
  A2_LIGHTWATER_CONDUCTIVE: {
    id: 'A2_LIGHTWATER_CONDUCTIVE',
    act: 2,
    label: 'Eau conductrice',
    desc: 'L eau lumineuse peut alimenter les relais et puzzles.',
  },
  A2_UPPER_WORLD_SIGNAL_CONFIRMED: {
    id: 'A2_UPPER_WORLD_SIGNAL_CONFIRMED',
    act: 2,
    label: 'Signal du monde superieur',
    desc: 'Le ciel laisse apparaitre des silhouettes au-dessus du dome.',
  },
  A2_IRON_COLOSSUS_DEFEATED: {
    id: 'A2_IRON_COLOSSUS_DEFEATED',
    act: 2,
    label: 'Colosse de Fer vaincu',
    desc: 'Orval reste semi-active et les racines profanees commencent a bouger.',
  },
};

export const QUEST_DEFS = {
  // Act I - main line
  A1_MQ01: {
    id: 'A1_MQ01',
    title: 'Le bruit sous le puits',
    act: 1,
    order: 101,
    main: true,
    startsActive: true,
    desc: 'Aide Mael a reparer le puits bloque sous Auge-Basse.',
    steps: [
      { id: 'reach-well', desc: 'Atteindre le vieux puits', type: 'proximity', x: 8, z: 8, radius: 8 },
      { id: 'clear-creature', desc: 'Eliminer la creature du puits', type: 'kill', enemyType: 'scout', count: 1 },
    ],
    reward: { xp: 120, items: ['lumen-sample'] },
    worldFlags: ['A1_WELL_REPAIRED'],
    unlockQuests: ['A1_MQ02', 'A1_SQ_MAEL'],
  },
  A1_MQ02: {
    id: 'A1_MQ02',
    title: 'Les enfants qui brillent',
    act: 1,
    order: 102,
    main: true,
    prerequisites: ['A1_MQ01'],
    desc: 'Retrouve les enfants partis suivre des lucioles bleues sous la pierre.',
    steps: [
      { id: 'find-children', desc: 'Explorer les Collines du Suif', type: 'proximity', x: -24, z: 28, radius: 10 },
      { id: 'secure-hill', desc: 'Nettoyer le camp proche', type: 'kill', enemyType: 'scout', count: 2 },
    ],
    reward: { xp: 150, items: ['lumen-sample'] },
    worldFlags: ['A1_LUMEN_WATER_HINT'],
    unlockQuests: ['A1_MQ03', 'A1_SQ_CHILDREN'],
  },
  A1_MQ03: {
    id: 'A1_MQ03',
    title: 'Carte d un monde trop petit',
    act: 1,
    order: 103,
    main: true,
    prerequisites: ['A1_MQ02'],
    desc: 'Aide Nara a activer trois bornes de cartographie anciennes.',
    steps: [
      { id: 'north-marker', desc: 'Activer la borne nord', type: 'proximity', x: 0, z: -50, radius: 10 },
      { id: 'east-marker', desc: 'Activer la borne est', type: 'proximity', x: 40, z: 40, radius: 10 },
      { id: 'west-marker', desc: 'Activer la borne ouest', type: 'proximity', x: -60, z: -20, radius: 10 },
    ],
    reward: { xp: 180, items: ['survivor-map'] },
    worldFlags: ['A1_CARTOGRAPHY_TRIANGLE_ON'],
    unlockQuests: ['A1_MQ04', 'A1_SQ_NARA'],
  },
  A1_MQ04: {
    id: 'A1_MQ04',
    title: 'Le sceau sur la langue',
    act: 1,
    order: 104,
    main: true,
    prerequisites: ['A1_MQ03'],
    desc: 'Escorte Soeur Eliane jusqu a un autel interdit des Gardiens du Sceau.',
    steps: [
      { id: 'reach-seal-altar', desc: 'Atteindre l autel du Sceau', type: 'proximity', x: 25, z: 20, radius: 8 },
      { id: 'defend-eliane', desc: 'Defendre Eliane', type: 'kill', enemyType: 'armored', count: 1 },
    ],
    reward: { xp: 180, items: ['faction-seal'] },
    worldFlags: ['A1_GUARDIANS_CONTACT'],
    unlockQuests: ['A1_MQ05', 'A1_SQ_SEAL'],
  },
  A1_MQ05: {
    id: 'A1_MQ05',
    title: 'Le voleur de ciel',
    act: 1,
    order: 105,
    main: true,
    prerequisites: ['A1_MQ04'],
    desc: 'Poursuis Ix, messager des Heritiers de la Rupture.',
    steps: [
      { id: 'catch-ix-trail', desc: 'Suivre la trace d Ix', type: 'proximity', x: -42, z: 36, radius: 10 },
      { id: 'break-ambush', desc: 'Briser l embuscade', type: 'kill', enemyType: 'scout', count: 3 },
    ],
    reward: { xp: 180, items: ['rupture-mark'] },
    worldFlags: ['A1_RUPTURE_CONTACT'],
    unlockQuests: ['A1_MQ06', 'A1_SQ_RUPTURE'],
  },
  A1_MQ06: {
    id: 'A1_MQ06',
    title: 'Vael-Dorn s ouvre',
    act: 1,
    order: 106,
    main: true,
    prerequisites: ['A1_MQ05'],
    desc: 'Rassemble trois clefs de drainage pour ouvrir l archive souterraine.',
    steps: [
      { id: 'drain-key-east', desc: 'Recuperer la clef est', type: 'proximity', x: 60, z: -20, radius: 8 },
      { id: 'drain-key-west', desc: 'Recuperer la clef ouest', type: 'proximity', x: -50, z: 45, radius: 8 },
      { id: 'drain-key-guard', desc: 'Vaincre le porteur de clef', type: 'kill', enemyType: 'armored', count: 2 },
    ],
    reward: { xp: 240, items: ['drain-key', 'drain-key', 'drain-key'] },
    worldFlags: ['A1_DRAIN_KEYS_COMPLETE'],
    unlockQuests: ['A1_MQ07'],
  },
  A1_MQ07: {
    id: 'A1_MQ07',
    title: 'L Archive qui respire',
    act: 1,
    order: 107,
    main: true,
    prerequisites: ['A1_MQ06'],
    desc: 'Explore Vael-Dorn et lis l archive du Gutter.',
    steps: [
      { id: 'enter-vael-dorn', desc: 'Entrer dans Vael-Dorn', type: 'proximity', x: 45, z: 45, radius: 8 },
      { id: 'read-archive', desc: 'Lire l archive centrale', type: 'proximity', x: 52, z: 52, radius: 5 },
    ],
    reward: { xp: 300, items: ['memory-shard'] },
    worldFlags: ['A1_VAEL_DORN_ARCHIVE_READ'],
    unlockQuests: ['A1_MQ08'],
  },
  A1_MQ08: {
    id: 'A1_MQ08',
    title: 'La Fracture du Ciel',
    act: 1,
    order: 108,
    main: true,
    prerequisites: ['A1_MQ07'],
    desc: 'Survis a l activation du moteur-coeur de Vael-Dorn.',
    steps: [
      { id: 'touch-engine-heart', desc: 'Toucher le moteur-coeur', type: 'proximity', x: 56, z: 56, radius: 6 },
      { id: 'escape-archive', desc: 'Sortir de l archive fracturee', type: 'proximity', x: 40, z: 40, radius: 10 },
    ],
    reward: { xp: 360, items: ['sky-fracture-proof'] },
    worldFlags: ['SKY_DOME_FIRST_CRACK'],
    unlockQuests: ['A1_MQ09', 'A1_SQ_RUST'],
  },
  A1_MQ09: {
    id: 'A1_MQ09',
    title: 'Ceux qui veulent refermer',
    act: 1,
    order: 109,
    main: true,
    prerequisites: ['A1_MQ08'],
    desc: 'Stabilise les urgences provoquees par la Fracture.',
    steps: [
      { id: 'save-civilians', desc: 'Secourir les civils d Auge-Basse', type: 'proximity', x: 0, z: 0, radius: 12 },
      { id: 'seal-gravity-pocket', desc: 'Stabiliser une poche de gravite', type: 'proximity', x: 35, z: 35, radius: 12 },
      { id: 'defeat-fractured', desc: 'Eliminer les veilleurs fissures', type: 'kill', enemyType: 'armored', count: 3 },
    ],
    reward: { xp: 320, items: ['lumen-sample'] },
    worldFlags: ['A1_POST_FRACTURE_PRIORITY_CIVILIAN'],
    unlockQuests: ['A1_MQ10'],
  },
  A1_MQ10: {
    id: 'A1_MQ10',
    title: 'Le Gardien des Cendres',
    act: 1,
    order: 110,
    main: true,
    prerequisites: ['A1_MQ09'],
    desc: 'Affronte le Gardien des Cendres au Chantier des Anges.',
    steps: [
      { id: 'reach-angel-yard', desc: 'Atteindre le Chantier des Anges', type: 'proximity', x: 72, z: 48, radius: 12 },
      { id: 'break-guardian', desc: 'Vaincre le Gardien des Cendres', type: 'kill', enemyType: 'elite', count: 1 },
    ],
    reward: { xp: 450, items: ['celestial-lock-fragment'] },
    worldFlags: ['A1_ASH_GUARDIAN_DEFEATED'],
    unlockQuests: ['A1_MQ11'],
  },
  A1_MQ11: {
    id: 'A1_MQ11',
    title: 'Dire ou cacher',
    act: 1,
    order: 111,
    main: true,
    prerequisites: ['A1_MQ10'],
    desc: 'Annonce la verite sur le ciel faux a Auge-Basse.',
    steps: [
      { id: 'return-to-auge-basse', desc: 'Retourner a Auge-Basse', type: 'proximity', x: 0, z: 0, radius: 10 },
    ],
    reward: { xp: 250, items: ['truth-token'] },
    worldFlags: ['A1_TRUTH_PUBLIC'],
    setAct: 2,
    unlockQuests: ['A2_MQ01'],
  },

  // Act I - side arcs
  A1_SQ_CHILDREN: {
    id: 'A1_SQ_CHILDREN',
    title: 'Les enfants du filtre',
    act: 1,
    order: 151,
    prerequisites: ['A1_MQ02'],
    desc: 'Apaise les voix que les enfants entendent dans l eau lumineuse.',
    steps: [
      { id: 'find-drawings', desc: 'Trouver les dessins des enfants', type: 'proximity', x: -18, z: 12, radius: 8 },
      { id: 'memory-under-bridge', desc: 'Suivre la voix sous le pont', type: 'proximity', x: -28, z: 18, radius: 8 },
    ],
    reward: { xp: 180, items: ['memory-shard'] },
    worldFlags: ['A1_CHILDREN_VOICES_CALMED'],
  },
  A1_SQ_NARA: {
    id: 'A1_SQ_NARA',
    title: 'Les cartes qui mentent',
    act: 1,
    order: 152,
    prerequisites: ['A1_MQ03'],
    desc: 'Aide Nara a refaire sa carte apres la revelation des bornes.',
    steps: [
      { id: 'scan-anomaly-one', desc: 'Scanner la premiere anomalie', type: 'proximity', x: 18, z: -34, radius: 8 },
      { id: 'scan-anomaly-two', desc: 'Scanner la zone sans nord', type: 'proximity', x: -44, z: -44, radius: 10 },
    ],
    reward: { xp: 210, items: ['survivor-map'] },
    worldFlags: ['A1_SECRET_CARTOGRAPHER_TRUTH'],
  },
  A1_SQ_MAEL: {
    id: 'A1_SQ_MAEL',
    title: 'Le prix du calme',
    act: 1,
    order: 153,
    prerequisites: ['A1_MQ01'],
    desc: 'Decouvre ce que Mael a cache pour eviter la panique.',
    steps: [
      { id: 'find-hidden-bodies', desc: 'Trouver le charnier', type: 'proximity', x: -12, z: -28, radius: 8 },
      { id: 'defeat-lieborn', desc: 'Vaincre la creature nee du mensonge', type: 'kill', enemyType: 'mutant', count: 1 },
    ],
    reward: { xp: 220, items: ['rune-fragment'] },
    worldFlags: ['A1_MAEL_TRUTH_EXPOSED'],
  },
  A1_SQ_RUST: {
    id: 'A1_SQ_RUST',
    title: 'Les cloches de rouille',
    act: 1,
    order: 154,
    prerequisites: ['A1_MQ08'],
    desc: 'Recupere les morceaux d une cloche divine tombee du ciel.',
    steps: [
      { id: 'bell-piece-one', desc: 'Recuperer le premier morceau', type: 'proximity', x: 64, z: 20, radius: 8 },
      { id: 'bell-piece-two', desc: 'Recuperer le second morceau', type: 'proximity', x: 80, z: -10, radius: 8 },
      { id: 'bell-piece-three', desc: 'Recuperer le troisieme morceau', type: 'proximity', x: 20, z: 68, radius: 8 },
    ],
    reward: { xp: 260, items: ['rust-bell'] },
    worldFlags: ['A1_SECRET_BELL_COMPLETE'],
  },
  A1_SQ_SEAL: {
    id: 'A1_SQ_SEAL',
    title: 'Les mensonges utiles',
    act: 1,
    order: 155,
    prerequisites: ['A1_MQ04'],
    desc: 'Aide Eliane a detruire des preuves dangereuses.',
    steps: [
      { id: 'erase-proof-one', desc: 'Detruire la premiere preuve', type: 'proximity', x: 30, z: 16, radius: 8 },
      { id: 'erase-proof-two', desc: 'Detruire la seconde preuve', type: 'proximity', x: 44, z: 22, radius: 8 },
    ],
    reward: { xp: 170, items: ['faction-seal'] },
    worldFlags: ['A1_SEAL_LIES_ACCEPTED'],
  },
  A1_SQ_RUPTURE: {
    id: 'A1_SQ_RUPTURE',
    title: 'Les portes qui n existent pas',
    act: 1,
    order: 156,
    prerequisites: ['A1_MQ05'],
    desc: 'Suis Ix vers des portes visibles seulement pres de l eau lumineuse.',
    steps: [
      { id: 'find-invisible-door', desc: 'Trouver la porte invisible', type: 'proximity', x: -54, z: 50, radius: 8 },
      { id: 'open-shortcut', desc: 'Ouvrir le raccourci fracture', type: 'proximity', x: -70, z: 54, radius: 8 },
    ],
    reward: { xp: 210, items: ['rupture-mark'] },
    worldFlags: ['A1_RUPTURE_SHORTCUT_OPEN'],
  },

  // Act II - main line
  A2_MQ01: {
    id: 'A2_MQ01',
    title: 'La premiere pluie',
    act: 2,
    order: 201,
    main: true,
    prerequisites: ['A1_MQ11'],
    desc: 'Escorte les refugies vers le Camp du Paratonnerre.',
    steps: [
      { id: 'reach-iron-road', desc: 'Atteindre la Route des Cendres Hautes', type: 'proximity', x: 90, z: 55, radius: 14 },
      { id: 'protect-refugees', desc: 'Repousser les blindes', type: 'kill', enemyType: 'armored', count: 3 },
    ],
    reward: { xp: 320, items: ['living-iron'] },
    worldFlags: ['A2_IRONRAIN_STARTED'],
    unlockQuests: ['A2_MQ02'],
  },
  A2_MQ02: {
    id: 'A2_MQ02',
    title: 'Le camp sous l aiguille',
    act: 2,
    order: 202,
    main: true,
    prerequisites: ['A2_MQ01'],
    desc: 'Repare le paratonnerre du camp avec Brann Oxydal.',
    steps: [
      { id: 'reach-camp', desc: 'Atteindre le Camp du Paratonnerre', type: 'proximity', x: 105, z: 60, radius: 12 },
      { id: 'gather-conductors', desc: 'Recuperer du metal vivant', type: 'pickup', itemId: 'living-iron', count: 1 },
    ],
    reward: { xp: 260, items: ['storm-rod'] },
    worldFlags: ['A2_LIGHTWATER_CONDUCTIVE'],
    unlockQuests: ['A2_MQ03', 'A2_SQ_BRANN', 'A2_SQ_NARA'],
  },
  A2_MQ03: {
    id: 'A2_MQ03',
    title: 'Deux plans pour une tour',
    act: 2,
    order: 203,
    main: true,
    prerequisites: ['A2_MQ02'],
    desc: 'Survis a l echec de la reunion entre Eliane et Ix.',
    steps: [
      { id: 'reach-parley', desc: 'Atteindre la table de negociation', type: 'proximity', x: 80, z: 60, radius: 10 },
      { id: 'break-raid', desc: 'Briser le raid sur le camp', type: 'kill', enemyType: 'scout', count: 4 },
    ],
    reward: { xp: 280, items: ['faction-mark'] },
    worldFlags: ['A2_FACTION_SPLIT_VISIBLE'],
    unlockQuests: ['A2_MQ04', 'A2_SQ_ELIANE', 'A2_SQ_IX'],
  },
  A2_MQ04: {
    id: 'A2_MQ04',
    title: 'Le relais des Lames',
    act: 2,
    order: 204,
    main: true,
    prerequisites: ['A2_MQ03'],
    desc: 'Stabilise le premier relais dans les Champs de Lames.',
    steps: [
      { id: 'reach-blades', desc: 'Entrer dans les Champs de Lames', type: 'proximity', x: 120, z: 35, radius: 12 },
      { id: 'defeat-ferric-captain', desc: 'Vaincre le Capitaine Ferrique', type: 'kill', enemyType: 'elite', count: 1 },
    ],
    reward: { xp: 360, items: ['orval-relay-core'] },
    worldFlags: ['A2_RELAY_BLADES_ON'],
    unlockQuests: ['A2_MQ05'],
  },
  A2_MQ05: {
    id: 'A2_MQ05',
    title: 'Le frere de la forge',
    act: 2,
    order: 205,
    main: true,
    prerequisites: ['A2_MQ04'],
    desc: 'Explore la Forge Sans Main pour retrouver le frere de Brann.',
    steps: [
      { id: 'enter-forge', desc: 'Entrer dans la Forge Sans Main', type: 'proximity', x: 112, z: -24, radius: 12 },
      { id: 'clear-forge', desc: 'Neutraliser les soldats de forge', type: 'kill', enemyType: 'armored', count: 4 },
    ],
    reward: { xp: 380, items: ['living-iron', 'forge-heart'] },
    worldFlags: ['A2_FORGE_SURVIVOR_SAVED'],
    unlockQuests: ['A2_MQ06'],
  },
  A2_MQ06: {
    id: 'A2_MQ06',
    title: 'L eau qui se souvient du ciel',
    act: 2,
    order: 206,
    main: true,
    prerequisites: ['A2_MQ05'],
    desc: 'Suis une riviere lumineuse jusqu a une memoire pre-dome.',
    steps: [
      { id: 'follow-lumen-river', desc: 'Suivre la riviere lumineuse', type: 'proximity', x: 72, z: 86, radius: 12 },
      { id: 'read-pre-dome', desc: 'Lire la memoire pre-dome', type: 'proximity', x: 60, z: 96, radius: 8 },
    ],
    reward: { xp: 360, items: ['pre-dome-memory'] },
    worldFlags: ['A2_PRE_DOME_MEMORY_FOUND'],
    unlockQuests: ['A2_MQ07'],
  },
  A2_MQ07: {
    id: 'A2_MQ07',
    title: 'Le relais des Noyes',
    act: 2,
    order: 207,
    main: true,
    prerequisites: ['A2_MQ06'],
    desc: 'Reactive le relais sous la zone noyee d eau lumineuse.',
    steps: [
      { id: 'reach-drowned-relay', desc: 'Atteindre le relais noye', type: 'proximity', x: -40, z: 90, radius: 12 },
      { id: 'calm-memory-guards', desc: 'Apaiser les gardes memoire', type: 'kill', enemyType: 'mutant', count: 3 },
    ],
    reward: { xp: 400, items: ['orval-relay-core'] },
    worldFlags: ['A2_RELAY_DROWNED_PURIFIED'],
    unlockQuests: ['A2_MQ08', 'A2_SQ_MEMORY'],
  },
  A2_MQ08: {
    id: 'A2_MQ08',
    title: 'Ceux d en haut regardent',
    act: 2,
    order: 208,
    main: true,
    prerequisites: ['A2_MQ07'],
    desc: 'Decode le signal venu du dome avec Nara.',
    steps: [
      { id: 'reach-signal-post', desc: 'Atteindre le poste de signal', type: 'proximity', x: 88, z: -36, radius: 12 },
      { id: 'defeat-observer', desc: 'Vaincre l observateur celeste', type: 'kill', enemyType: 'elite', count: 1 },
    ],
    reward: { xp: 420, items: ['upper-world-signal'] },
    worldFlags: ['A2_UPPER_WORLD_SIGNAL_CONFIRMED'],
    unlockQuests: ['A2_MQ09'],
  },
  A2_MQ09: {
    id: 'A2_MQ09',
    title: 'Le relais du Tonnerre Mort',
    act: 2,
    order: 209,
    main: true,
    prerequisites: ['A2_MQ08'],
    desc: 'Active le dernier relais dans le cimetiere des machines.',
    steps: [
      { id: 'dead-thunder-yard', desc: 'Atteindre le Tonnerre Mort', type: 'proximity', x: 132, z: -60, radius: 14 },
      { id: 'clear-machine-yard', desc: 'Nettoyer le cimetiere de machines', type: 'kill', enemyType: 'armored', count: 5 },
    ],
    reward: { xp: 430, items: ['orval-relay-core'] },
    worldFlags: ['A2_RELAY_DEAD_THUNDER_ON'],
    unlockQuests: ['A2_MQ10'],
  },
  A2_MQ10: {
    id: 'A2_MQ10',
    title: 'Orval demande un nom',
    act: 2,
    order: 210,
    main: true,
    prerequisites: ['A2_MQ09'],
    desc: 'Entre dans Orval et reponds a son identification.',
    steps: [
      { id: 'enter-orval', desc: 'Entrer dans la Tour d Orval', type: 'proximity', x: 150, z: 70, radius: 14 },
      { id: 'answer-orval', desc: 'Atteindre la Voix d Orval', type: 'proximity', x: 158, z: 72, radius: 8 },
    ],
    reward: { xp: 450, items: ['orval-name-token'] },
    worldFlags: ['A2_ORVAL_PLAYER_NAMED'],
    unlockQuests: ['A2_MQ11'],
  },
  A2_MQ11: {
    id: 'A2_MQ11',
    title: 'Refermer ou stabiliser',
    act: 2,
    order: 211,
    main: true,
    prerequisites: ['A2_MQ10'],
    desc: 'Choisis une methode temporaire pour controler Orval.',
    steps: [
      { id: 'choose-stabilize', desc: 'Stabiliser Orval avec Nara et Brann', type: 'proximity', x: 150, z: 70, radius: 10 },
    ],
    reward: { xp: 300, items: ['orval-stabilizer'] },
    worldFlags: ['A2_ORVAL_PLAN_STABILIZE'],
    unlockQuests: ['A2_MQ12'],
  },
  A2_MQ12: {
    id: 'A2_MQ12',
    title: 'Le Colosse de Fer',
    act: 2,
    order: 212,
    main: true,
    prerequisites: ['A2_MQ11'],
    desc: 'Affronte le protecteur d Orval.',
    steps: [
      { id: 'reach-colossus-core', desc: 'Atteindre le coeur de la tour', type: 'proximity', x: 166, z: 78, radius: 12 },
      { id: 'defeat-colossus', desc: 'Vaincre le Colosse de Fer', type: 'kill', enemyType: 'elite_territorial', count: 1 },
    ],
    reward: { xp: 700, items: ['iron-colossus-memory', 'celestial-lock-fragment'] },
    worldFlags: ['A2_IRON_COLOSSUS_DEFEATED', 'A2_COLOSSUS_APPEASED'],
    setAct: 3,
  },

  // Act II - side arcs
  A2_SQ_BRANN: {
    id: 'A2_SQ_BRANN',
    title: 'Le metal a memoire',
    act: 2,
    order: 251,
    prerequisites: ['A2_MQ02'],
    desc: 'Aide Brann a forger une arme qui garde l emotion de son porteur.',
    steps: [
      { id: 'collect-alloy', desc: 'Collecter un alliage vivant', type: 'pickup', itemId: 'living-iron', count: 1 },
      { id: 'test-memory-blade', desc: 'Tester la lame memoire', type: 'kill', enemyType: 'armored', count: 2 },
    ],
    reward: { xp: 280, items: ['memory-forged-blade'] },
    worldFlags: ['A2_BRANN_MEMORY_METAL_FORGED'],
  },
  A2_SQ_NARA: {
    id: 'A2_SQ_NARA',
    title: 'La carte de pluie',
    act: 2,
    order: 252,
    prerequisites: ['A2_MQ02'],
    desc: 'Construis avec Nara une carte qui predit la pluie de fer.',
    steps: [
      { id: 'scan-rain-one', desc: 'Scanner le premier front de pluie', type: 'proximity', x: 96, z: 88, radius: 10 },
      { id: 'scan-rain-two', desc: 'Scanner le second front de pluie', type: 'proximity', x: 132, z: 34, radius: 10 },
    ],
    reward: { xp: 260, items: ['rain-map'] },
    worldFlags: ['A2_SECRET_IRONRAIN_SHELTER_NET'],
  },
  A2_SQ_ELIANE: {
    id: 'A2_SQ_ELIANE',
    title: 'Les villages a sacrifier',
    act: 2,
    order: 253,
    prerequisites: ['A2_MQ03'],
    desc: 'Organise une troisieme route d evacuation pour eviter le sacrifice.',
    steps: [
      { id: 'open-third-route', desc: 'Ouvrir la troisieme route', type: 'proximity', x: 74, z: 112, radius: 12 },
      { id: 'hold-route', desc: 'Tenir la route contre les blindes', type: 'kill', enemyType: 'armored', count: 3 },
    ],
    reward: { xp: 320, items: ['guardian-oath'] },
    worldFlags: ['A2_ELIANE_THIRD_ROUTE_OPEN'],
  },
  A2_SQ_IX: {
    id: 'A2_SQ_IX',
    title: 'La porte dans l orage',
    act: 2,
    order: 254,
    prerequisites: ['A2_MQ03'],
    desc: 'Suis Ix dans une tempete qui promet une sortie du Gutter.',
    steps: [
      { id: 'storm-door', desc: 'Trouver la porte dans l orage', type: 'proximity', x: 138, z: 92, radius: 12 },
      { id: 'survive-storm', desc: 'Survivre aux veilleurs de l orage', type: 'kill', enemyType: 'mutant', count: 2 },
    ],
    reward: { xp: 320, items: ['rupture-mark'] },
    worldFlags: ['A2_RUPTURE_STORM_DOOR_OPEN'],
  },
  A2_SQ_MEMORY: {
    id: 'A2_SQ_MEMORY',
    title: 'Les soldats qui demandent pardon',
    act: 2,
    order: 255,
    prerequisites: ['A2_MQ07'],
    desc: 'Libere les souvenirs humains prisonniers des soldats de fer.',
    steps: [
      { id: 'find-memory-soldier', desc: 'Trouver un soldat memoire', type: 'proximity', x: -58, z: 96, radius: 10 },
      { id: 'release-memory-soldiers', desc: 'Liberer trois soldats memoire', type: 'kill', enemyType: 'mutant', count: 3 },
    ],
    reward: { xp: 360, items: ['memory-shard'] },
    worldFlags: ['A2_MEMORY_SOLDIERS_RELEASED'],
  },
};

export const ITEM_DEFS = {
  'lumen-sample': { id: 'lumen-sample', name: 'Echantillon de Lumen', type: 'material', icon: 'Crystal1.png', stackable: true },
  'memory-shard': { id: 'memory-shard', name: 'Eclat de Memoire', type: 'key', icon: 'Crystal5.png', stackable: false },
  'survivor-map': { id: 'survivor-map', name: 'Carte de Nara', type: 'key', icon: 'Parchment.png', stackable: false },
  'faction-seal': { id: 'faction-seal', name: 'Sceau des Gardiens', type: 'key', icon: 'Ring1.png', stackable: false },
  'faction-mark': { id: 'faction-mark', name: 'Marque de Faction', type: 'key', icon: 'Ring2.png', stackable: false },
  'rupture-mark': { id: 'rupture-mark', name: 'Marque de Rupture', type: 'key', icon: 'Ring2.png', stackable: false },
  'drain-key': { id: 'drain-key', name: 'Clef de Drainage', type: 'key', icon: 'Key1.png', stackable: true },
  'sky-fracture-proof': { id: 'sky-fracture-proof', name: 'Preuve de la Fracture', type: 'key', icon: 'Crystal4.png', stackable: false },
  'celestial-lock-fragment': { id: 'celestial-lock-fragment', name: 'Fragment de Verrou Celeste', type: 'key', icon: 'Crown.png', stackable: true },
  'truth-token': { id: 'truth-token', name: 'Serment de Verite', type: 'key', icon: 'Parchment.png', stackable: false },
  'rust-bell': { id: 'rust-bell', name: 'Cloche de Rouille', type: 'key', icon: 'Crown.png', stackable: false },
  'rune-fragment': { id: 'rune-fragment', name: 'Fragment de Rune', type: 'material', icon: 'Crystal4.png', stackable: true },
  'living-iron': { id: 'living-iron', name: 'Fer Vivant', type: 'material', icon: 'Mineral.png', stackable: true },
  'storm-rod': { id: 'storm-rod', name: 'Tige de Paratonnerre', type: 'key', icon: 'Key1.png', stackable: false },
  'orval-relay-core': { id: 'orval-relay-core', name: 'Coeur de Relais d Orval', type: 'key', icon: 'Crystal2.png', stackable: true },
  'forge-heart': { id: 'forge-heart', name: 'Coeur de Forge', type: 'key', icon: 'Crystal3.png', stackable: false },
  'pre-dome-memory': { id: 'pre-dome-memory', name: 'Memoire Pre-Dome', type: 'key', icon: 'Crystal5.png', stackable: false },
  'upper-world-signal': { id: 'upper-world-signal', name: 'Signal d En Haut', type: 'key', icon: 'Parchment.png', stackable: false },
  'orval-name-token': { id: 'orval-name-token', name: 'Nom Donne a Orval', type: 'key', icon: 'Ring1.png', stackable: false },
  'orval-stabilizer': { id: 'orval-stabilizer', name: 'Stabilisateur d Orval', type: 'key', icon: 'Key1.png', stackable: false },
  'iron-colossus-memory': { id: 'iron-colossus-memory', name: 'Memoire du Colosse', type: 'key', icon: 'Crystal5.png', stackable: false },
  'memory-forged-blade': { id: 'memory-forged-blade', name: 'Lame a Memoire', type: 'weapon', icon: 'Sword.png', stackable: false },
  'rain-map': { id: 'rain-map', name: 'Carte de Pluie', type: 'key', icon: 'Parchment.png', stackable: false },
  'guardian-oath': { id: 'guardian-oath', name: 'Serment du Sceau', type: 'key', icon: 'Ring1.png', stackable: false },
  'health-potion': { id: 'health-potion', name: 'Potion de Soin', type: 'consumable', icon: 'Potion1_Filled_Red.png', stackable: true, healAmount: 40 },
};

